[package]
name = "egui-material"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.32"
eframe = "0.32"
emath = "0.32"
epaint = "0.32"
ecolor = "0.32"
webbrowser = { version = "1.0.5", default-features = false }
egui-file-dialog = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"

[build-dependencies]
ureq = { version = "2.9", features = ["json"] }
serde_json = "1.0"
