[package]
name = "egui-material"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.32"
eframe = "0.32"
emath = "0.32"
epaint = "0.32"
ecolor = "0.32"
webbrowser = { version = "1.0.5", default-features = false }
